apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scalyr-agent-2
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: scalyr-agent-2
    spec:
      containers:
      - name: scalyr-agent
        image: scalyr/scalyr-k8s-agent
        imagePullPolicy: Always
        env:
          - name: SCALYR_API_KEY
            valueFrom:
              secretKeyRef:
                name: scalyr-api-key
                key: scalyr-api-key
          - name: HOSTNAME
            value: {{ .Values.hostname }}
        resources:
          limits:
            memory: 500Mi
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: dockersock
          mountPath: /var/scalyr/docker.sock
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      # comment this section if you do not want to run on the master
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
